src/utilities.jl
test/utilities.jl

To support changes made in https://github.com/alan-turing-institute/MLJ.jl/pull/179

Add rng argument to shuffle

---

src/utilities.jl

add `rng` in the signature of the `partition` function

minor docstring fix

---

Project.toml
src/MLJBase.jl
src/datasets.jl
src/init.jl
test/runtests.jl

This pull request makes the following changes:
1. Add Requires as a required dependency
2. Remove CSV as an required dependency
3. Use Requires to conditionally load the code in `src/datasets.jl`
4. Add CSV as a test-only dependency

Make CSV an optional dependency instead of a required dependency

---

Project.toml
src/MLJBase.jl
src/metadata_utilities.jl
src/mlj_model_macro.jl
src/utilities.jl
test/metadata_utilities.jl
test/mlj_model_macro.jl
test/runtests.jl

adds and exports
* `metadata_pkg` 
* `metadata_model`
* `@mlj_model`
from mljmodels. 
This PR will have to be synched with the removal PR from MLJModels so that dev branches remain in synch
I guess it would be fine to: 
1. merge and release this
1. update the project.toml on the dev branch of MLJModels to use mljbase >=5.1
1. merge and release the dev branch of mljmodels after merging the relevant PR

Utilsmigration

---

Project.toml

Merge dev branch for 0.6.0 release

---

Project.toml

To enable fast-track release of new versions.

Add [compat] bounds for all [deps]

---

src/distributions.jl
test/distributions.jl

ok this is essentially #65  with a fix; clearly my git-fu is so good that I wasn't able to just push there... anyway this should pass tests.

Oxinabox patch 1

---

src/MLJBase.jl
src/equality.jl
test/equality.jl

Add is_same_except method for MLJType

---

Project.toml
src/MLJBase.jl
src/equality.jl
test/equality.jl

- (**Bug fix**) Resolve problem with `==` for MLJType objects with nested fields (#74)

Patch release 0.7.3

---

Project.toml
src/MLJBase.jl
src/distributions.jl
src/equality.jl
test/distributions.jl
test/equality.jl

````julia
v = categorical(["yes", "maybe", "no", "yes"])
w = [1, 4, 5, 1] # some weights
d = fit(UnivariateFinite, v, w)
pdf(d, "maybe") ≈ 4/11 # true
````

Add facility to fit a Univariate to weighted samples

---

Project.toml
src/MLJBase.jl
src/distributions.jl
test/info.jl
test/runtests.jl
test/scientific_trait.jl

(**Bug fix**) Fix issue with failure to update `ScientificTypes.FUNCTION_GIVEN_TRAIT` dictionary (#85)

For patch release 0.7.5 

---

src/data.jl

Correct docstring for `classes` and tweak `int` and `classes` implementations

---

src/MLJBase.jl
test/runtests.jl
test/static.jl

[MLJ #70](https://github.com/alan-turing-institute/MLJ.jl/issues/291)

Add Static <: Unsupervised and fit fallback for transformers with no learning

---

src/MLJBase.jl
src/model_traits.jl
test/info.jl

See https://github.com/alan-turing-institute/MLJ.jl/issues/60
This PR breaks MLJModels (and so MLJ)

Add support for online learning

---

Project.toml

For tagged release 0.8.0

---

.travis.yml
src/data.jl
test/data.jl

add keyword to MLJBase.int

---

src/MLJBase.jl
test/runtests.jl

This PR add support for static  operations. An earlier PR on  this failed to merge properly and we are trying again.

Static again

---

src/data.jl
test/data.jl
test/measures/finite.jl
test/measures/measures.jl
test/mlj_model_macro.jl
test/utilities.jl

adding more tests
Also  fixed issues with `throws` which weren't throwing instances of the error.
This adds like 6% to coverage but it's the right path I feel; this base package should be in the  90s!!

more tests

---

src/MLJBase.jl
src/measures/measures.jl
test/measures/measures.jl

make aggregate on a scalar a non-operation

---

src/data.jl
test/data.jl

Address https://github.com/alan-turing-institute/MLJ.jl/issues/258

Tweak partition logic and add more rigorous tests

---

src/MLJBase.jl
test/MLJBase.jl
test/models/Constant.jl
test/runtests.jl

Add informative error mssg for some wrong uses of predict_mode, etc 

---

src/measures/continuous.jl
src/measures/finite.jl
src/measures/measures.jl
src/metadata_utilities.jl
test/measures/measures.jl

Implement distribution_type for probablisitic measures

---

src/data.jl
test/data.jl

Resolves https://github.com/alan-turing-institute/MLJ.jl/issues/407

informative DomainError for int 

---

Project.toml
src/one_dimensional_range_methods.jl
src/resampling.jl

Fixes load error caused by incorrect merge conflict resolution

For 0.10.1 release

---

src/measures/confusion_matrix.jl

Have labels use the permutation

---

Project.toml
src/MLJBase.jl
src/openml.jl
test/openml.jl
test/runtests.jl

OpenML.org API integration, the `OpenML.load()` function will download a dataset from the OpenML platform given its ID number, and return it as a `Vector` of `NamedTuples`.
For example, the iris dataset has the ID 61 in OpenML. The named tuples can be converted to tabular format such as a `DataFrame`.
```
iris_named_tuples = OpenML.load(61)
df = DataFrame(iris_named_tuples)
```

OpenML API

---

Project.toml
src/MLJBase.jl
src/data/data.jl
src/measures/finite.jl
src/openml.jl
test/data/data.jl
test/measures/finite.jl
test/measures/measures.jl
test/openml.jl

Allow shuffling in unpack

---

src/measures/confusion_matrix.jl
src/measures/registry.jl
src/resampling.jl
test/measures/finite.jl

Make confusion_matrix into a measure

---

Project.toml
src/operations.jl

context https://github.com/alan-turing-institute/MLJ.jl/issues/122#issuecomment-586806125

Bringing predict_median back

---

Project.toml
src/operations.jl

Bringing predict_median back (#197)

---

.gitignore
src/resampling.jl
test/resampling.jl

Reverts alan-turing-institute/MLJBase.jl#240

Revert "Spread remainder evenly among folds in train_test_pairs(::CV, ...)"

---

src/composition/composites.jl
src/machines.jl
src/operations.jl
test/composition/composites.jl

Restyle reports and fitted_params for composite models

---

test/composition/arrows.jl

Anticipate test break in julia 1.5 due to new rand! 

---

src/operations.jl
test/operations.jl
test/runtests.jl

Better errors for operations with no data argument 

---

src/interface/data_utils.jl

corresponds to https://github.com/alan-turing-institute/MLJModelInterface.jl/pull/39

implement `schema` interface

---

Project.toml
src/interface/data_utils.jl
src/machines.jl

For a 0.13.4 release

---

src/data/datasets_synthetic.jl
test/data/datasets_synthetic.jl

Remove constant column in make_regression with intercept=true

---

Project.toml
test/data/data.jl
test/hyperparam/one_dimensional_range_methods.jl
test/interface/data_utils.jl
test/interface/interface.jl

drop DataFrames from test dependencies

---

src/measures/loss_functions_interface.jl
src/univariate_finite/arrays.jl
src/univariate_finite/types.jl
test/measures/loss_functions_interface.jl
test/univariate_finite/arrays.jl

fix cat for UnivariateFiniteArray

---

src/resampling.jl

- added _acceleration parameter to `update` method of `Resampler` (Important omission)
- removed redundant `@sync` and `close` methods. (Turns out the lock in `close` method also contributed to the issue)
- Better workaround to the silent warnings issue for the `evaluate` method.
cc @ablaom

added _acceleration to Resampler update method

---

Project.toml

For a 0.14.2 release

---

Project.toml
src/composition/learning_networks/nodes.jl
src/openml.jl
src/operations.jl
src/resampling.jl
test/composition/models/deprecated.jl
test/operations.jl

For a 0.14.3 release

---

src/composition/models/pipelines.jl
src/data/data.jl
src/interface/model_api.jl
src/operations.jl
test/composition/learning_networks/machines.jl
test/composition/models/pipelines.jl

Fix predict_mode, etc for composite models

---

Project.toml

PR #375 to address https://github.com/alan-turing-institute/MLJ.jl/issues/607

For a 0.14.5 release

---

src/operations.jl

- fix some typos (e.g. replaced `fitresult.predict_mode(X)` with `fitresult.predict_mode(Xnew)`)
- added specific operations when dealing with `Machine{<:Static}` (e.g. this PR defines a specific method  `tranform(mach::Machine{<:Static}, Xraw, Xraw_more...)` to be used only for static machines while `transform(mach::Machine, Xraw)` will be used for all other machine types.)
- operations can be called on a `mach::Machine{<:Static}` (e.g. `tranform(mach, y1, y2)`)  even if the `mach` hasn't been fitted . This was done since `Static` models don't have any learned parameters.
@ablaom thoughts??

fix operations.jl

---

Project.toml
src/measures/finite.jl

Closes https://github.com/alan-turing-institute/MLJ.jl/issues/630#issuecomment-671167519

fixes signature for roc curve

---

src/composition/abstract_types.jl
src/operations.jl

Please see: https://github.com/alan-turing-institute/MLJ.jl/issues/642

Add the `:predict_joint` operation, and add composite and surrogate types for `JointProbabilistic`

---

src/composition/learning_networks/nodes.jl
src/machines.jl
src/sources.jl
test/composition/learning_networks/nodes.jl
test/composition/models/_wrapped_function.jl
test/composition/models/pipelines.jl

Improve error message for exception thrown by composite models 

---

src/MLJBase.jl

@ablaom Let me know if anything is missing.

Export `JointProbabilistic` and `predict_joint`

---

src/resampling.jl
src/univariate_finite/methods.jl
src/utilities.jl
test/resampling.jl

https://github.com/alan-turing-institute/MLJ.jl/issues/616
Also overloads `Distributions.params` for `UnivariateFinite` (minor addition I forgot to separate out)

Add report_per_fold and machine_per_fold to results of evaluate!()

---

src/univariate_finite/arrays.jl

see https://github.com/alan-turing-institute/MLJBase.jl/pull/418#issuecomment-683461141

improvements to pdf and logpdf broadcast methods

---

src/measures/continuous.jl
test/measures/continuous.jl

Uses the code suggestions by @pfarndt in #437.

Avoids `cosh` overflow and closes #437

---

src/machines.jl

Replace throw -> rethrow in fit!(::Machine, ...) 

---

Project.toml
src/machines.jl

For a 0.15.5 release

---

Project.toml
src/measures/finite.jl

For a 0.16.2 release

---

.github/workflows/ci.yml

Fix the docs deployment

---

docs/Project.toml
docs/make.jl

@DilumAluthge Docs: set `push_preview=false`

---

.github/workflows/ci.yml
src/init.jl
test/runtests.jl

Address MACHINE_CHANNEL issue

---

.github/workflows/ci.yml
Project.toml
README.md
src/data/data.jl
src/hyperparam/one_dimensional_range_methods.jl
src/init.jl
test/runtests.jl

For a 0.16.3 release

---

src/operations.jl
test/composition/learning_networks/nodes.jl
test/machines.jl
test/runtests.jl
test/static.jl

Better error for bad call of transform on machines for Static models

---

Project.toml
src/composition/learning_networks/machines.jl
test/composition/learning_networks/machines.jl
test/runtests.jl

Resolve learning machines issue

---

Project.toml
src/resampling.jl

Eliminate some logging noise in `evaluate!`

For a 0.17.3 release

---

Project.toml
src/MLJBase.jl
src/univariate_finite/arrays.jl
src/univariate_finite/methods.jl
src/univariate_finite/types.jl
test/_models/Transformers.jl
test/univariate_finite/arrays.jl

For a 0.17.4 release

---

Project.toml
test/runtests.jl

For a 0.17.6 release

---

Project.toml
src/composition/learning_networks/machines.jl
src/composition/models/inspection.jl
src/composition/models/methods.jl
test/composition/learning_networks/machines.jl
test/composition/models/from_network.jl
test/composition/models/inspection.jl
test/composition/models/methods.jl

For a 0.18.5 release

---

Project.toml
src/resampling.jl

This came up here: https://github.com/alan-turing-institute/MLJ.jl/issues/789

Fix error message for using deterministic measure with probabilistic model in `evaluate!`

---

Project.toml

Hopefully fixes intermittent bug reported at https://github.com/alan-turing-institute/MLJ.jl/issues/788e 
See also https://github.com/timholy/ProgressMeter.jl/issues/209#issuecomment-851780327

Bump compat ProgressMeter = "1.7.1" and version = "0.18.9"

---

Project.toml

For a 0.18.9 release

---

src/data/data.jl
test/data/data.jl

Also, relax signature of `partition(::AbstractVector, ...)` to allow any
vectors, not just vectors of integers.
Fix #361.

Add method `partition(::AbstractMatrix, ...)`

---

src/MLJBase.jl
src/measures/loss_functions_interface.jl
src/measures/measure_search.jl
src/measures/meta_utilities.jl
test/measures/loss_functions_interface.jl

Remove LossFunctions type piracy 

---

src/resampling.jl

Replacing length by nrows to solve #580

---

src/composition/models/stacking.jl

No changes to code here.
@olivierlabayle

Fix some formatting in stack doc-string and simplify a bit

---

Project.toml
src/interface/data_utils.jl
test/interface/data_utils.jl

For a 0.18.14 release

---

src/composition/models/stacking.jl

While reading the MLJ doc I realized I had missed to change the docstring relative to the resampling argument.

add docstring fix

---

src/resampling.jl

This is to address https://github.com/JuliaAI/MLJTuning.jl/issues/141

Remove model type parameter from `Resampler`

---

src/MLJBase.jl
src/composition/learning_networks/machines.jl
src/composition/learning_networks/nodes.jl
src/operations.jl
src/resampling.jl

Implementation of the proposed outlier detection draft with "Abstract" removed from the types for consistency.

Outlier Detection Integration

---

src/measures/finite.jl

This addresses #630 for multiclass FScores.

Use expanded formula of MulticlassFScore

---

Project.toml
test/interface/data_utils.jl
test/runtests.jl

Discovered that `test/interface/data_utils.jl` is not included in `runtests.jl`. 🙄

Reconnect some orphaned tests

---

src/measures/finite.jl
test/measures/finite.jl

Resolves feature request #569 .
However, added test is broken; an issue that is flagged in #651 
I also "fixed" the tests for the other versions of balanced accuracy, and marked as broken, until  #651 is resolved.

Add adjusted balanced accuracy 

---

src/measures/finite.jl
test/measures/finite.jl

Fix binary `FScore` corner case 

---

src/MLJBase.jl
src/composition/learning_networks/inspection.jl
src/composition/learning_networks/nodes.jl
src/composition/models/pipelines.jl
src/composition/models/pipelines2.jl
src/sources.jl
src/utilities.jl
test/composition/models/pipelines.jl
test/composition/models/pipelines2.jl
test/runtests.jl
test/sources.jl
test/utilities.jl

Macro free pipelines (PR onto `for-0-point-19-release`)

---

src/utilities.jl
test/utilities.jl

Fix `sequence_string` bug 

---

test/runtests.jl

It should be possible to conditionally test some sub-modules.
Edit: This PR allows us to call `Pkg.test` with test arguments, e.g. `Pkg.test("MLJBase", test_args=["interface"])` would only run the interface tests.

Implement conditional testing

---

src/data/data.jl
test/measures/measures.jl

Remove empty collection catch in aggregation of measurements

---

src/measures/README.md
src/measures/continuous.jl
src/measures/measures.jl
src/measures/meta_utilities.jl

Rsquared fix plus more docs

---

src/data/data.jl
test/data/data.jl
test/hyperparam/one_dimensional_range_methods.jl

See #621  which this PR resolves.

Modify `unpack` to return an extra value with all remaining columns

---

src/hyperparam/one_dimensional_range_methods.jl
src/hyperparam/one_dimensional_ranges.jl
test/hyperparam/one_dimensional_range_methods.jl
test/hyperparam/one_dimensional_ranges.jl

Change `:log` default for unbounded range scales to `:log10`

---

src/data/data.jl
test/data/data.jl

Add synchronised partitioning of multiple objects 

---

Project.toml
src/resampling.jl

Fix PerformanceEvaluation bug

---

.github/workflows/ci.yml
Project.toml
README.md

For a 0.19.1 release

---

.github/workflows/ci.yml
Project.toml
src/MLJBase.jl
src/interface/data_utils.jl
test/interface/data_utils.jl

For a 0.19.2 release

---

src/composition/models/pipelines.jl
test/composition/models/pipelines.jl

To solve https://github.com/JuliaAI/MLJBase.jl/issues/710

add target_scitype trait for supervised pipelines

---

.github/workflows/ci.yml
Project.toml
src/MLJBase.jl
src/measures/doc_strings.jl
src/measures/finite.jl
src/measures/measures.jl
test/measures/doc_strings.jl
test/runtests.jl

Add docstrings for instances (aliases) of docstrings

---

src/MLJBase.jl
src/measures/README.md
src/measures/finite.jl
src/measures/loss_functions_interface.jl
src/measures/measure_search.jl
src/measures/meta_utilities.jl
src/measures/probabilistic.jl
test/measures/loss_functions_interface.jl

Programmatically export measure types, type aliases, and built-in instances

---

src/MLJBase.jl

Additionally requires https://github.com/JuliaAI/CategoricalDistributions.jl/pull/24

Fix CategoricalDistributions.jl reexports

---

.github/workflows/ci.yml
Project.toml
src/MLJBase.jl

Probably should wait for:
#735

For a 0.19.6 release

---

src/measures/finite.jl
test/measures/finite.jl

I am new to contributing to open source repositories. Please let me know if there is something else that I need to do or if there is scope for improvement. Thanks.

Added Kappa Measure

---

src/composition/learning_networks/nodes.jl
src/sources.jl

Fix docs for nodes

---

src/measures/finite.jl
test/measures/finite.jl
test/resampling.jl

Skip `NaN` in averaging in `MulticlassFScore`

---

src/hyperparam/one_dimensional_ranges.jl

Fix show for one-dimensional ranges

---

Project.toml
src/operations.jl
test/composition/models/static_transformers.jl

For a 0.20.15 release

---

src/composition/models/pipelines.jl
src/composition/models/stacking.jl
src/measures/measures.jl

As part of the JuliaCon hackathon, I've fixed some typos that I've noticed in the docs - spelling of `probabilistic` in this case.
No changes made to active code - only docs/comments.

Fix typo probab i listic

---

src/composition/models/stacking.jl

This PR only changes whitespace.

Get rid of long lines in stacking.jl

---

src/MLJBase.jl
src/composition/models/stacking.jl
src/machines.jl
src/models.jl
test/composition/models/stacking.jl
test/models.jl
test/runtests.jl

Add `check_ismodel` method and use it in `Stack` to improve error messages

---

Project.toml
src/machines.jl
test/composition/models/methods.jl
test/machines.jl

For a 0.20.17 release

---

src/composition/models/pipelines.jl
src/composition/models/transformed_target_model.jl
test/composition/models/pipelines.jl
test/composition/models/static_transformers.jl
test/composition/models/transformed_target_model.jl

Related: #806 
Also closes: #855

Re-implement `TransformedTargetModel` as `NetworkComposite` model

---

src/composition/models/pipelines.jl
test/composition/learning_networks/machines.jl
test/composition/models/pipelines.jl

Re-implement pipelines as `NetworkComposite` models

---

src/MLJBase.jl

Export `restore!`

---

Project.toml
src/composition/learning_networks/signatures.jl
src/show.jl

For a 0.21.6 release

---

src/operations.jl

To close #874.
Tested using MLJTestIntegration.jl

Address relaxation in requirements for `reformat`

---

Project.toml
src/measures/continuous.jl
src/measures/probabilistic.jl
test/measures/probabilistic.jl

For a 0.27.8 release

---

src/resampling.jl

- purge refs to obsolete functionality

Remove redundant code

---

Project.toml
src/interface/data_utils.jl

For a 1.8.1 release
