JuliaAI/MLJBase.jl

.travis.yml
Project.toml
src/MLJBase.jl
src/data.jl
src/datasets.jl
src/datasets_requires.jl
src/info.jl
src/init.jl
src/loss_functions_interface.jl
src/measures.jl
src/model_traits.jl
src/show.jl
src/utilities.jl
test/data.jl
test/datasets.jl
test/info.jl
test/loss_functions_interface.jl
test/measures.jl
test/runtests.jl

- Bump ScientificTypes requirement to v0.2.0
- (Enhancement) The performance measures API (built-in measures +
adaptor for external measures) from MLJ has been migrated to MLJBase.
MLJ.
- (Breaking) `info`, which returns a dictionary (needed for TOML
serialization) is renamed to `info_dic`. In this way "info" is
reserved for a method in MLJModels/MLJ that returns a
more-convenient named-tuple
- (Breaking) The `is_probabilistic` model trait is replaced with
`prediction_type`, which can have the values `:deterministic`,
`:probabilistic` or `:interval`, to allow for models predicting real
intervals, and for consistency with measures API.
- (Bug fix, mildly breaking) The `package_license` model trait is now included in
`info_dict` in the case of unsupervisd models.
- (Enhancement, mildly …

Lots of little improvements

---

src/metadata_utilities.jl
test/metadata_utilities.jl

Addresses the first part of #58 by using `parentmodule`. This now works (has been tested) for modules, internal modules, and main (so all use cases).
Once that's merged and released, I'll  use it in MLJModels builtin transformers for instance (where  it was previously failing)
It also closes #57

fix for metadata using parentmodule

---

src/distributions.jl

Before
```
UnivariateFinite(f=>0.313470891723578, m=>0.686529108276422)
```
After
```
UnivariateFinite(f=>0.313, m=>0.687)
```
**Note**: uses *sigdigits* rounding so if there are very low numbers, they won't get zeroed but showed as `5.67e-5`:
```
julia> round(0.00001351035, sigdigits=3)
1.35e-5
```

using significant digits rounding in show of univariatefinite

---

src/datasets.jl

I have gone over the ames (and reduced ames) with a fine tooth comb to determine the most appropriate scitype conversions, adding appropriate levels for ordered factors that are not numeric in the raw.
I've tested the changes break nothing on the current dev branches of MLJBase, MLJModels and MLJ. 
@tlienart Can you check if this effects MLJTutorials, and possibly do a superficial review of this PR? This is not super urgent.

Ames dataset update

---

src/data.jl
test/data.jl

Context: #151 
Row/column tables are native julia types implementing the Tables.jl API
A row table is a vector of named tuples with identical type parameters.
A column table is a named tuple of equi-length vectors.

Improve performance of selectrows for DataFrames and row/colum tables

---

src/measures/finite.jl
test/measures/finite.jl

* additional tests comparing with  sklearn `brier_score_loss` and `log_loss`
* clamping of `pdf(d, y)` in `_cross_entropy` to `[eps(), 1-eps()]` to avoid numerical issues
* get rid of stray  `Any[ŷ...]` which are not necessary as far as I can tell
* allow passing a clamping epsilon to cross entropy (most likely this won't be used but it matches what sklearn  provides)

Reduce risk of numerical issues with cross entropy and additional tests

---

src/measures/measures.jl
test/measures/measures.jl

The minor bug is this:
If `target_scitype(model) = AbstractVector{<:Continuous}` instead of `target_scitype(model) = AbstractVector{Continuous}` then `default_measure(model) = nothing` in cases it should be `rms` (say). This is despite the fact that `Continuous` actually has no proper subtypes.

minor refactor of default_measure to address #51 and a minor bug

---

.travis.yml
src/MLJBase.jl
src/resampling.jl
test/resampling.jl
test/runtests.jl
test/test_utilities.jl

Fix resampling race condition, and so forth

---

Project.toml
README.md
src/MLJBase.jl
src/measures/confusion_matrix.jl
src/measures/finite.jl
src/operations.jl
test/measures/confusion_matrix.jl
test/measures/measures.jl

For a 0.11.8 release

---

.travis.yml

Yaqub helpfully noticed that 1.0 was not on the travis CI, it should be I guess.

adding 1.0  in the CI

---

Project.toml
src/hyperparam/one_dimensional_range_methods.jl
test/hyperparam/one_dimensional_range_methods.jl

Minor update adding methods for samplers to the `scale` function (currently implemented for one-dimensional ranges only).

For 0.12.2 release

---

.gitignore
.travis.yml
docs/Project.toml
docs/make.jl
docs/src/composition.md
docs/src/datasets.md
docs/src/distributions.md
docs/src/index.md
docs/src/measures.md
docs/src/openml.md
docs/src/resampling.md
docs/src/utilities.md
src/openml.jl

This is some initial setup for MLJBase API docs.
Notes:
- `matrix` has been changed to `jobs` per this recommendation: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/index.html#Travis-CI-1
- There are couple of warnings in docs build section, honestly do not know how to solve them, but it seems that final docs are fine
- One should of course setup DOCUMENTER_KEY and all other things in repo and travis CI. Also I do not know at what point travis creates `stable` version in `gh-pages`, I think simpliest solution is just to add copy of `dev` folder manually in `gh-pages` branch. 
- Unfortunately I do not know intrinsic details of MLJBase, so some docs were rather loosely put to categories, hope that's ok.
Result can be found here: https://arkoniak.github.io/MLJBase.jl/dev/

Documentation update for github pages

---

src/resampling.jl

After my last PR i decided to push the limits of the progress meter display. This lead me to make the following four changes.
1. limit the buffer size of the `RemoteChannel` to a maximum of 1000. This is to limit the size of memory allocated which may affect performance of the program depending on the platform it is ran on. This choice follows that used in [ProgressMeter](https://github.com/timholy/ProgressMeter.jl) codebase.
2. Added a yield() in the case of `CPU1` and `CPUThreads`. This is to ensure smooth updating of the progress bar especially in the case of `CPUThreads.
3. Added an  Info message in the case of `CPUThreads` similar to `CPUProcesses` to tell the user the number of threads being used.
4. Add fallback to `CPU1` when `nthreads==1`. This was done to smooth-en the display …

improve progressmeter display

---

Project.toml

Bump to 0.13.0

---

src/operations.jl

Stop throwing error when calling an operation (eg, `transform`) on a `Static` model's machine, as there are no learned parameters.

Remove error message for running fit! on a Static transformer

---

Project.toml
src/composition/networks.jl
src/operations.jl
src/resampling.jl
test/composition/arrows.jl
test/operations.jl
test/resampling.jl
test/runtests.jl

Fixes #248.
Benchmark between `dev` and this PR:
```julia
using BenchmarkTools
scv = StratifiedCV(nfolds=5);
N = 10_000_000;
rows = 1:(10N);
y = (
vcat(fill(:a, N), fill(:b, 2N), fill(:c, 3N), fill(:d, 4N))
|> shuffle
|> categorical
);
@btime MLJBase.train_test_pairs_old($scv, $rows, $y);
@btime MLJBase.train_test_pairs_new($scv, $rows, $y);
```

Update train_test_pairs() for stratified CV 

---

src/resampling.jl

I thought of a way to somewhat simplify the stratified CV code. It's still basically the same algorithm, but a little easier to read. The performance is about the same:
```julia
scv = StratifiedCV(nfolds=5)
N = 10_000_000
rows = 1:(10N)
y = (
vcat(fill(:a, N), fill(:b, 2N), fill(:c, 3N), fill(:d, 4N))
|> shuffle
|> categorical
);
```
```julia
julia> @btime MLJBase.train_test_pairs_current($scv, $rows, $y);
9.728 s (146 allocations: 4.84 GiB)
julia> @btime MLJBase.train_test_pairs_simplified($scv, $rows, $y);
9.478 s (243 allocations: 5.59 GiB)
```

Simplify stratified CV

---

src/resampling.jl
test/resampling.jl

This PR does 2 things.
1. Removes  the use of channels for displaying progress meters  for `CPU1` and `CPUThreads`. Channels are still being used for `CPUProcesses`
2. Makes progress meter display  functionality compatible with that of `MLJTuning` (PR fro this would be created at MLJTuning soonest)

removed channels for CPU1 and CPUThreads

---

Project.toml
src/interface/univariate_finite.jl
src/resampling.jl

Remove use of channels for displaying progress meter in `CPU1` and `CPUProcesses` versions of resampling  (PR #283 )

For a 0.10.3 release

---

src/composition/composites.jl

kinda same as https://github.com/alan-turing-institute/MLJModels.jl/pull/246
This PR allows end users to create `@pipeline`s without adding MLJBase.jl and MLJModelInterface.jl in their enviroments.
`@pipeline` would just work after `using MLJ`, while testing for this package doesn't require it.

no explicit MLJBase requirementfor creating @pipeline

---

src/MLJBase.jl

clean up & export `StaticTransformer` correctly (MLJ.jl re-exports this, but it's currently just an undefined)
closes https://github.com/alan-turing-institute/MLJ.jl/issues/518

clean up and correct export 

---

src/resampling.jl

This switches from `floor` to `cld`. Meaning no more than `n_threads` tasks are spawned.

switch to cld

---

src/MLJBase.jl
src/resampling.jl
src/utilities.jl
test/resampling.jl
test/utilities.jl

Closes issue #300 .
1. `CPUThreads` now accepts an (Optional) integer (e.g `CPUThreads(5)` ) which can be used to control the number of threads that are spawned (as spawning threads has some overhead). Most times the default parameters do the trick.
2. A `Chunks` iterator is implemented to help (1) above.
3. The return values of `_evaluate` method now has the right type (You could check this if you like)
1. `CPU1()` can be used in all cases
2. when using `CPUThreads(n) or CPUThreads()` speed up is only present if the data is small and model involves heavy computations. The package implementing the code for the model must be thread safe. The magnitude of the speedup depends on the number of threads.
3. when using `CPUProcesses` speed up is only present if the data is small and model …

replace unsafe use of dict in Multithreaded code.

---

src/resampling.jl

currently the current implementation boxes `channels` and `progressmeter` (because of the way they are defined and later used in closures passed to `mapreduce`) . This PR fixes that. 
Also the previous code does `[measurements_matrix[:,k]...]` which has unnecessary allocations (@ablaom is there any reason for this). I replaced with `measurements_matrix[:,k]` which has same behaviour(i.e creates a copy)
```julia
julia> A = permutedims(reshape(rand(100), (1,100)));
julia> @btime [$(A)[:,1]...]
3.491 μs (102 allocations: 3.31 KiB)
julia> @btime $(A)[:,1]
184.344 ns (1 allocation: 896 bytes)
```

avoid Unboxing and mem alloc 

---

src/resampling.jl

The current implementation of `_evaluate!(func, mach, accel::CPUThreads, nfolds, verbosity` shares the state of `mach.model` across all threads. 
But the call to the`fit!` method from `_evaluate` calls `clean!(model)` which mutates the model(a shared state) on each thread causing data race(due to reading and writing from different threads). This so far hasn't caused any issues but there's no telling what would happen when more threads are used. Hence informing the decision to create a clone of the model on each thread(I really still don't like copying)
Another option is to maybe to call the `clean!` method outside the threads (To clean up) so subsequent calls to `clean` within `Threads.@spawn` would only be reading (provided mutation doesn't occur on a previously cleaned model i.e it …

create a model for each thread

---

Project.toml
src/utilities.jl
test/utilities.jl

From the doc-string:
available_name(modl::Module, name::Symbol)
Function to replace, if necessary, a given `name` with a
modified one that ensures it is not the name of any existing object in
the global scope of `modl`. Modifications are created with numerical
suffixes.

Add naming utility

---

src/composition/learning_networks/nodes.jl
test/composition/learning_networks/nodes.jl

Currently `@node f(node, not_a_node)` spits the dummy if `node` or `not_a_node` are not defined in global scope. This PR fixes this by assuming anything not in global scope is an `AbstractNode`. 
So, for example, the tests for this macro, which previously failed if wrapped in a `@testset` block, now pass. 
For cases where even this does not work, the user still has the `node` *function*. 
Here's the revised doc-string:
---
@node f(...)
Construct a new node that applies the function `f` to some combination
of nodes, sources and other arguments.
*Important.* An argument not in global scope is assumed to be a node
or source.
```
X = source(π)
W = @node sin(X)
julia> W()
0
X = source(1:10)
Y = @node selectrows(X, 3:4)
julia> Y()
3:4
julia> Y([:one, :two, :three, :four])
2-element …
```

Tweaks to @node macro to make it usable outside global scope

---

src/openml.jl

Column names with hyphens are replaced with underscores in datasets from OpenML.
Resolves https://github.com/alan-turing-institute/MLJ.jl/issues/579

Hyphens are replaced by underscores in column names from OpenML

---

Project.toml
src/operations.jl
test/composition/models/deprecated.jl
test/operations.jl

This PR reverts the behaviour of `predict` and other operations when provided `rows=...` keyword. In latest minor release this triggers a dep warning. 
There had been some objections to removing this syntax and on further review it seems we can live with this.

Dump deprecation predict rows

---

src/operations.jl

This makes the `predict_mode`, `predict_mean`, and `predict_median` code more concise in the case of surrogate and composite models.
cc: @ablaom 
cc: @tlienart

Make some code more concise

---

src/interface/model_api.jl

```julia
using MLJ
julia> implemented_methods(UnivariateStandardizer())
6-element Array{Symbol,1}:
:fit              
:fitted_params    
:inverse_transform
:inverse_transform
:transform        
:transform      
```
The corresponding entries in model registry will require an MLJModels registry `@update` and new MLJModels patch.

Eliminate multiple entries for `implement_methods` trait

---

.github/workflows/CompatHelper.yml

@ablaom 
Just FYI, these changes won't go into effect until the next time you merge `dev` into `master`.

CompatHelper: open PRs against `dev`

---

src/MLJBase.jl
src/univariate_finite/arrays.jl
src/univariate_finite/methods.jl
test/univariate_finite/arrays.jl
test/univariate_finite/methods.jl

Take 2!
This just adds a `logpdf` method and some tests. `logpdf` is needed for MCMC sampling with SossMLJ: https://github.com/cscherrer/SossMLJ.jl/issues/68

Add logpdf method for UnivariateFinite

---

src/univariate_finite/arrays.jl
test/univariate_finite/arrays.jl

I feel that PR #411 left out some methods. I feel these methods are needed since we want `logpdf` to have similar functionality with `pdf` the difference being just the `log`.
So this PR Adds `logpdf.(u::UniFinArr{S,V,R,P,N}, v::AbstractArray{<:CategoricalValue{V,R},N})` and 
`logpdf.(u::UniFinArr{S,V,R,P,N}, raw::Union{V,AbstractArray{V,N}})` methods.
Feel free to close this if u feel these method are not needed.

added logpdf.(u, v) and logpdf.(u, raw) methods

---

src/hyperparam/one_dimensional_ranges.jl
test/hyperparam/one_dimensional_ranges.jl

Improves the `range` doc-string and adds a check that at least one of the following keywords is specified: `[values, lower, upper, origin, unit]`.

Add a minor check to the arguments of range

---

Project.toml
src/univariate_finite/methods.jl
test/univariate_finite/methods.jl

The changes in Distributions 0.24 (more precisely, https://github.com/JuliaStats/Distributions.jl/pull/1171) require some additional dispatches to avoid method ambiguity errors (as seen e.g. in https://github.com/alan-turing-institute/MLJBase.jl/pull/431).
This PR supersedes https://github.com/alan-turing-institute/MLJBase.jl/pull/431.

Support Distributions 0.24

---

src/MLJBase.jl
src/measures/finite.jl
src/measures/measures.jl
test/measures/finite.jl

Resolves the merge conflicts in #455. 
Other changes:
- Change default averaging to `macro_avg` (from `no_avg`)
- Rename `MulticlassNPV` to `MulticlassNegativePredictiveValue`
- Change `AbstractVector` option for `return_type` to `Vector` 
- In anticipation of #450, name the measures and anchor their document strings using types rather than an instances
- Further corrections and clean ups to doc-strings
- Fix some tests and add some tests
For the release notes:
---
Add the multiclass classification measures (applying to any `Finite` target):
-  `MulticlassFalseNegative`, `MulticlassFalsePositive`,  `MulticlassTrueNegative`, `MulticlassTruePositive`. When instances are called, as in `MulticlassFalseNegative()(yhat, y)`, then they return a dictionary keyed on class, or a vector , according …

Multiclass 3

---

README.md
src/MLJBase.jl
src/composition/models/pipelines.jl
src/measures/confusion_matrix.jl
src/measures/continuous.jl
src/measures/finite.jl
src/measures/loss_functions_interface.jl
src/measures/measure_search.jl
src/measures/measures.jl
src/measures/meta_utilities.jl
test/info_dict.jl
test/measures/confusion_matrix.jl
test/measures/continuous.jl
test/measures/finite.jl
test/measures/loss_functions_interface.jl
test/measures/measure_search.jl
test/measures/measures.jl

This PR resolves #450:
```julia
julia> measures()
59-element Array{NamedTuple{(:name, :instances, :human_name, :target_scitype, :supports_weights, :prediction_type, :orientation, :reports_each_observation, :aggregation, :is_feature_dependent, :docstring, :distribution_type, :supports_class_weights),T} where T<:Tuple,1}:
(name = Accuracy, instances = [accuracy], ...)
(name = AreaUnderCurve, instances = [area_under_curve, auc], ...)
(name = BalancedAccuracy, instances = [balanced_accuracy, bacc, bac], ...)
(name = BrierLoss, instances = [brier_loss], ...)
(name = BrierScore, instances = [brier_score], ...)
(name = ConfusionMatrix, instances = [confusion_matrix, confmat], ...)
(name = FScore, instances = [f1score], ...)
(name = FalseDiscoveryRate, instances = [false_discovery_rate, …
```

Cleanup the measures (aka loss functions and scores)

---

Project.toml
src/measures/loss_functions_interface.jl

Between these versions of LossFunctions, `ScaledDistanceLoss` went from a type to a function. Auto-generation of the list of distance losses in MLJ was not robust to this. This PR explicitly lists the losses to be re-exported to address this, and to head off similar problems in future.

Address breaking change in LossFunctions between 0.6 and 0.6.2

---

src/MLJBase.jl
src/composition/learning_networks/inspection.jl
src/measures/finite.jl
src/measures/measures.jl
src/resampling.jl
src/univariate_finite/arrays.jl
src/utilities.jl

This PR addresses a few things that the VS Code linter uncovered.
The linter also recommends using `x === nothing` rather than `x == nothing`. (Actually, I prefer to use `isnothing`.)
Also, there appear to be a few whitespace changes. I have my editor set up to strip trailing whitespace characters when I save a file.

Address a few things uncovered by the VS Code linter

---

docs/make.jl
docs/src/index.md

Docs build should still work even if `push_preview=false`.
`push_preview` should only affect PR previews. It should have no effect on pushes to `master`.

Docs: set `push_preview=false`

---

src/machines.jl
test/interface/model_api.jl

This PR removes the dimension check for `X, y` in `machine(model, X, y)` if `X === nothing`, allowing us to tweak the API for models that fit a distrubution. It also adds a check that the new API can be implemented without problems. 
This PR is non-breaking.

Relax dimension check in machine constructor

---

src/composition/models/pipelines.jl

In the MLJ pipeline error message, the word ```assignment``` is misspelled as ```assignement```. This PR fixes that!
Here's a screenshot of the error message

Fixed a spelling mistake in pipeline error message

---

.github/workflows/ci.yml

This will be useful for CompatHelper. On Julia nightly, CompatHelper workflows will now fail if they are not able to use the new version of the dependency.
This feature requires Julia 1.7, and thus is currently only available in Julia nightly.

Run CI on Julia nightly

---

Project.toml
src/interface/data_utils.jl
test/resampling.jl

bump compat CategoricalArrays = "0.9, 0.10"; level -> levelcode

---

src/resampling.jl
test/resampling.jl

This PR fixes a bug in the `Resampler` code. Recall that `Resampler` is a model wrapper for repetitive performance evaluation of models and is used by the `TunedModel` and `IterativeModel` wrappers, although it is not a public object. 
Here is how the bug manifests at present: Suppose you are tuning a single hyper-parameter using the `resampling=Holdout(rng=123)` option for the resampling strategy. Then you expect a single randomised train/test pair of rows to be created, and for the same pair to be used for each hyper-parameter value to be evaluated. However, at present, for each new hyper-parameter value, a new train/test pair of rows is generated. As the RNG has evolved after each evaluation, this new pair is *different* each time!
If one is not shuffling, then the bug does not …

Ensure Resampler does not generate new train/test pairs unless `resampling` or `repeats` changes

---

test/_models/NearestNeighbors.jl

Recall that MLJBase has its own local versions of models for testing. In some new tests in another PR, a small issue arises from the return type of KNNClassifier not being quite right, and this PR fixes this.
This only effects test code.

Tighten return type of predict for KNNClassifier (model for testing)

---

src/measures/finite.jl
test/measures/finite.jl

`den1` and `den2` are `Int`, when they get large enough multiplying them can
result in overflow.  The solution is to convert them to float before multiplying
them and computing the square root.
Fix #381.

Fix computation of Matthews correlation coefficient

---

src/measures/loss_functions_interface.jl
test/measures/loss_functions_interface.jl

Fix transposed `y` and `yhat` in measures from LossFunctions

---

src/interface/data_utils.jl
test/interface/data_utils.jl

Improve performance of `MMI.nrow` for high-dimensional tables.

improve performance of `MMI.nrows`

---

src/measures/loss_functions_interface.jl
test/measures/measures.jl

Show for some LossFunctions loss functions is broken  because of the non-uniform interface for accessing the parameter of a loss from LossFunctions.jl - sometimes a field, sometimes a type parameter.
This PR addresses this issue.

Fix show for some LossFunctions measures

---

src/MLJBase.jl
src/data/data.jl
src/univariate_finite/arrays.jl
src/univariate_finite/methods.jl
test/univariate_finite/arrays.jl
test/univariate_finite/methods.jl

By "cousins" I mean the various broadcasted versions we have implemented, and at the `logpdf` variations.
This is needed for #616

Implement `pdf(::UnivariateFinite, ::Missing) = missing` and cousins

---

src/MLJBase.jl
src/measures/confusion_matrix.jl
src/measures/finite.jl
src/measures/measures.jl
test/measures/finite.jl
test/measures/measures.jl

This PR addresses part of #616.
It includes adapting the general aggregation methods, such as  `(::Sum)()`, to handle to skip missing values.

Allow finite measures, incl confmat, to handle missing values

---

src/MLJBase.jl
src/measures/continuous.jl
src/measures/finite.jl
src/measures/measures.jl
test/measures/continuous.jl
test/measures/measure_search.jl

Adds `InfiniteSphericalScore` and `InfiniteLogScore`.
This PR also combines the `ContinuousBrierScore` and `CountBrierScore` into a single `InfiniteBrierScore`. These are from the recent PR #395 has been merged to dev but not master.

Add `Infinite` versions of the proper scoring rules spherical, log

---

src/measures/finite.jl
test/measures/finite.jl

The previous version was returning negative values for **true negatives**:
- Confusion Matrix
- Old _mtn function:
- New _mtn function:
Source: https://stats.stackexchange.com/a/338240/306362

Multiclass true negative of the conf_mat fix :)

---

src/measures/confusion_matrix.jl

fixed bug in `_confmat` method causing errors in julia 1.6.3. These errors were reported by a user on slack.

fix bug in `_confmat`

---

src/hyperparam/one_dimensional_ranges.jl
src/resampling.jl
src/show.jl
src/sources.jl
src/utilities.jl
test/measures/measures.jl

This PR carries out some tweaks to the way MLJBase displays objects:
- suppress `@423` business except for source nodes (https://github.com/alan-turing-institute/MLJ.jl/issues/842)
- suppress blue colouring of objects (leave some bold)
- fix some extraneous characters appearing in evaluation objects 
- #532

Display tweaks

---

src/interface/model_api.jl
test/interface/model_api.jl

Resolves first part of  #656.
Used to throw an error:
```julia
using MLJ
model = (@load GMMClusterer)()
X, _ = make_moons()
mach = machine(model, X) |> fit!
julia> predict_mode(mach, rows=1:2)
2-element CategoricalArrays.CategoricalArray{Int64,1,UInt32}:
2
1
```
cc @juliohm

Extend overloading of `predict_mode`, etc to all models, not just `Supervised`

---

src/machines.jl

Unsupervised annotators can be called in both a supervised and unsupervised fashion.

Fix input checks for unsupervised annotators

---

.github/workflows/ci.yml
src/composition/models/pipelines2.jl
src/utilities.jl
test/composition/models/pipelines2.jl
test/utilities.jl

Previously this didn't' work:
```julia
model = NeuralNetworkClassifier
pipe = Standardizer() |> model
mach = machine(pipe, (@load_iris)...) |> fit!
julia> training_losses(mach)
10-element Vector{Float64}:
1.1617235772453105
1.1391298992309888
1.1353015649469138
1.118214804032455
1.0628404657351944
1.0259886932644746
1.0157579569196977
0.9370889236524335
0.9723838495187639
0.9687408965584012
```
Also, the pipeline now knows the iteration parameter, which is now nested:
```julia
julia> iteration_parameter(pipe)
:(neural_network_classifier.epochs)
```
Which means pipelines play nicely with `IteratedModel`.

Allow automatic access to `training_losses` in iterative models wrapped in a pipeline

---

src/MLJBase.jl
src/measures/continuous.jl
test/measures/continuous.jl
test/resampling.jl
test/runtests.jl

This PR adds the R² metric.
R² is more informative for linear regressions than MSE and RMSE (Chicco et al, [2021](https://doi.org/10.7717/peerj-cs.623)) because the scale is dimensionless (a percentage).
I value -3 in the test is manually calculated by me. All looks good.
EDIT: It doesn't work yet in CV. I get an `_check(::RSquare, Vector{Int})`. I'll debug it tonight or so

Add R-square (coefficient of determination)

---

src/composition/models/transformed_target_model.jl
src/machines.jl
test/composition/models/transformed_target_model.jl

If a type is provided then `fit` changes this to the default instance.
Otherwise a warning is issued, which is not that helpful to realize one's mistake.

Allow `target` to be a model *type* in `TransformedTargetModel`

---

src/MLJBase.jl
src/interface/data_utils.jl
test/interface/data_utils.jl

Depends on https://github.com/JuliaAI/MLJModelInterface.jl/pull/133. Add's the `FullInterface` implementation of the `MLJModelInterface.scitype` method. 
cc. @ablaom

extend MLJModelInterface.scitype method

---

src/composition/learning_networks/inspection.jl
src/composition/learning_networks/machines.jl
src/composition/learning_networks/nodes.jl
src/composition/models/from_network.jl
src/composition/models/pipelines.jl
src/operations.jl
src/sources.jl
test/composition/learning_networks/machines.jl
test/composition/models/from_network.jl
test/composition/models/methods.jl
test/composition/models/pipelines.jl
test/sources.jl

In the recent implementation of `Pipeline` we introduced `ErrorNode <: AbstractNode` as a mechanism for throwing errors when an `UnsupervisedPipeline` did not support `inverse_transform`. This is not part of the public API.
This PR:
- Get's rid of `ErrorNodes` by allowing one to instead wrap an `Exception` object in an ordinary `Source` node. Calling the node in that case always *throws* the exception . This is a minor conceptual simplification. It also makes the next fix a little more straightforward. 
-  Fixes a bug in `replace`. This is an internal method used only for composite models exported using `@from_network`. The bug concerns the corner case where an "operation node" is also a `Source` node, and when there were previously `ErrorNode`s. 
**Some details.** The main change to …

Get rid of `ErrorNode`s and fix corner case bug in `replace`

---

src/composition/models/stacking.jl
test/composition/models/stacking.jl

I have played around with the stack again. Related to the new functionality [permitting to expose the internal state of a learning network](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Exposing-internal-state-of-a-learning-network) that you offered in 0.19. The goal would be to optionally report the internal cross validation result of the stack for a given set of measures.
Even though not complete, I think the following provides a poc for this. Before moving forward I wanted to see if you could give me some feedback and guidance on where to go next. A few ideas that come to my mind:
- Formatting of the report, maybe something matching the output of `evaluate!`?
- Maybe I should check that the measures match the stack type?
I hope you can find some time to look into …

Stacking internal evaluation

---

src/interface/model_api.jl

In support of https://github.com/JuliaAI/MLJSerialization.jl/pull/17 .
Note PR is onto `for-a-0-point-20-release` branch, not onto `dev`.
cc @olivierlabayle

Drop `filename` arg from save(filename, model, ...)

---

src/machines.jl
test/_models/MultivariateStats.jl
test/composition/learning_networks/nodes.jl
test/composition/models/deprecated.jl
test/composition/models/pipelines.jl
test/composition/models/stacking.jl
test/machines.jl

Continuation of #731.
Needs: 
@pazzo83 Be good if you review this (the most recent commits). The main problems fixed in this continuation are:
- A [bug](https://github.com/JuliaAI/MLJModelInterface.jl/pull/137) in MLJModelInterface for constructing the fallback for `fit_data_scitype` for supervised models supporting weights (so not part of this PR, but partly responsible for failure of tests in #731)
- Flawed logic for testing presence of `Unknown` in `fit_data_scitype`. This is now a separate function `_contains_unknown` with tests.
- `check_model_scitype` was not returning the value of `nowarns`
- a lot of logging checks needed updating
The difficulties encountered in #731 are due in some part to a lack of testing of the `check_model_scitype` "fallback" we are now using as the main …

Refactor model scitype check2

---

src/composition/models/stacking.jl
test/composition/models/stacking.jl

Unless I am missing something I think the existing version of `getfolds` is restrictive. 
This is a simple extension of the capabilities of resampling schemes. 
@edit 
I am converting to draft as I am also trying to get rid of the assumption that the resampling method needs a `nfolds` field and rely only on `train_test_pairs`.

make the stack's resampling scheme more general

---

src/resampling.jl

User on slack wanted to `evaluate!` a model with a bad `prediction_type`: the model predicts probabilities but the trait `prediction_type` was reporting otherwise. This PR helps such a user discover a workaround.

Add suggestion to `err_incompatible_prediction_types` message

---

src/measures/confusion_matrix.jl
test/measures/confusion_matrix.jl

This PR addresses a corner case for `confmat(y1, y2)` when `y1` and `y2` have `CategoricalValue` eltype but aren't actually categorical arrays. Previously, the following would fail:
```julia
bag = categorical(collect("abc"));
julia> y = CategoricalArrays.CategoricalValue{Char, UInt32}[bag[1], bag[1]]
2-element Vector{CategoricalValue{Char, UInt32}}:
'a'
'a'
julia> confmat(y, y)
┌ Warning: The classes are un-ordered,
│ using order: ['a', 'b', 'c'].
│ To suppress this warning, consider coercing to OrderedFactor.
└ @ MLJBase ~/MLJ/MLJBase/src/measures/confusion_matrix.jl:124
┌─────────────────────────────────────────┐
│              Ground Truth               │
┌─────────────┼─────────────┬─────────────┬─────────────┤
│  Predicted  │      a      │      b      │      c      │ …
```

Fix a problem with confmat and CategoricalValue eltype

---

src/resampling.jl
test/resampling.jl

According to the `show` output, `PerformanceEvaluation` has a field `train_test_pairs` whereas this should actually be `train_test_rows`.
Should I also add a test to check whether all `fieldnames(PerformanceEvaluation)` are contained in the output of `show`?

Fix wrong field name in a `show` method

---

src/MLJBase.jl
src/machines.jl
src/measures/measures.jl
src/resampling.jl
src/show.jl

This PR tweaks a few anomalies for `show(::MLJType)` and attempts to addresses https://github.com/alan-turing-institute/MLJ.jl/issues/923.
**edited to reflect final proposal:**
Type parameters now omitted in short display, but first hyper-parameter shown instead, for consistency with the long `MIMIE("text/plain")` display shown first below:
```
julia> Standardizer()
Standardizer(
features = Symbol[], 
ignore = false, 
ordered_factor = false, 
count = false)
julia> [Standardizer(), ConstantRegressor()]
2-element Vector{Model}:
Standardizer(features = Symbol[], …)
ConstantRegressor(distribution_type = Distributions.Normal)
```
Display like models:
```julia
julia> macro_f1score
MulticlassFScore(
β = 1.0, 
average = MLJBase.MacroAvg(), 
return_type = LittleDict)
julia> [macro_f1score, …
```

Improve short version of `show` for measures

---

src/resampling.jl
test/resampling.jl

Suggestion to add the standard deviation to the `PerformanceEvaluation` output:
```
┌────────────────────────────────┬───────────┬─────────────┬────────┬──────────────────────────────────────┐
│ measure                        │ operation │ measurement │ std    │ per_fold                             │
├────────────────────────────────┼───────────┼─────────────┼────────┼──────────────────────────────────────┤
│ LogLoss(                       │ predict   │ 0.704       │ 0.0135 │ [0.732, 0.7, 0.7, 0.7, 0.696, 0.696] │
│   tol = 2.220446049250313e-16) │           │             │        │                                      │
└────────────────────────────────┴───────────┴─────────────┴────────┴──────────────────────────────────────┘
```
This is useful to spot more easily how much variation …

Add std to show for `PerformanceEvaluation`

---

src/resampling.jl

This pull request contains minor changes in `resampling.jl`.
The changes const of:
1. Fixing a bug in the `resampling` code example showing a vector of tuples
2. Improve the documentation to use "vector of tuples" instead of "vector of pairs" to prevent confusion with the `Pair` datatype
3. Improve the error message in case a wrong type was supplied for the `resampling` keyword

Fix bugs and inconsistencies in documentation on `evaluate!`s `resampling` keyword

---

src/MLJBase.jl
src/machines.jl
test/machines.jl

This PR implements `feature_importances` method that returns a list of feature=>importance pairs for fitted machines with underlying models that supports intrinsic feature importances. (i.e models that overload the `reports_feature_importances` trait.)
**This Requires**

Add `feature_importances` machine inspection method.

---

src/composition/learning_networks/machines.jl
src/composition/models/methods.jl
test/composition/models/from_network.jl
test/composition/models/methods.jl

Traces of data in machines are now removed at time of serialisation (see [docs](https://alan-turing-institute.github.io/MLJ.jl/dev/machines/#Saving-machines)). Carried over from the old way of handling data anonymization there remains some gymnastics to shift data in and out of sources nodes in the learning networks used in composite models. This PR removes this redundant code and testing.
@olivierlabayle

Remove apparatus to anonymize composite model fitresults

---

src/composition/models/pipelines.jl
src/machines.jl
src/operations.jl
test/_models/Constant.jl
test/_models/DecisionTree.jl
test/_models/MultivariateStats.jl
test/_models/NearestNeighbors.jl
test/_models/Transformers.jl
test/composition/models/pipelines.jl
test/machines.jl

Previously the following code threw an error:
```julia
using MLJBase, MLJModels
mutable struct StaticKefir <: Static
alpha::Float64 # non-zero to be invertible
end
kefir(x, alpha) = x > 0 ? x * alpha : x / alpha
MLJBase.transform(model::StaticKefir, _, X) = broadcast(kefir, model.alpha, X)
MLJBase.inverse_transform(model::StaticKefir, _, W) = broadcast(kefir, 1/(model.alpha), W)
X = randn(20)
pipe = StaticKefir(3) |> Standardizer() |> StaticKefir(5) |> Standardizer()
mach = machine(pipe, X)
fit!(mach, verbosity=0)
```
This PR resolves the error. Behaviour is as expected, as seen from added tests:
```julia
@test inverse_transform(mach, transform(mach, X)) ≈ X
@test transform(mach, inverse_transform(mach, X)) ≈ X
```
This PR also changes the machine constructor for `Static` models so that …

Fix `inverse_transform` bug for pipelines with `Static` components

---

src/composition/models/pipelines.jl
src/composition/models/transformed_target_model.jl
test/composition/models/pipelines.jl

After this PR, the following code works again:
```julia
mutable struct MyDeterministic <: Deterministic
x::Symbol
end
MLJBase.fit(::MyDeterministic, args...) = nothing, nothing, nothing
MLJBase.predict(m::MyDeterministic, ::Any, Xnew) = fill(:dp, nrows(Xnew))
MLJBase.supports_training_losses(::Type{<:MyDeterministic}) = true
MLJBase.iteration_parameter(::Type{<:MyDeterministic}) = :x
MLJBase.training_losses(::MyDeterministic, report) = ones(3)
model = MyDeterministic(:bla)
tmodel = TransformedTargetModel(model, target=Standardizer)
pipe = Standardizer() |> tmodel
__, _, rp = MLJBase.fit(pipe, 0, X, y)
training_losses(pipe, rp)
ERROR: type NamedTuple has no field basic
Stacktrace:
[1] getproperty
@ ./Base.jl:42 [inlined]
[2] training_losses(model::MLJBase.TransformedTargetModelDeterministic …
```

Fix bug around training losses for pipelines

---

src/operations.jl
test/composition/models/static_transformers.jl

At present only `transform` is overloaded. In clustering algorithms that do not generalize to new data, such as DBSCAN, we also need `predict`, for consistency with clustering models that *do* generalize (as `transform` is "reserved" for dimension reduction). This PR overloads all operations that can be called on `Static` models to work for `Static` machines as well.

Overload all operations (`predict`, `predict_mode`, etc) for use on `Static` machines

---

src/composition/models/stacking.jl
test/composition/models/stacking.jl

Adapt stack to allow missings in a basemodel `target_scitype`

---

src/composition/models/stacking.jl
src/machines.jl

Closes #817
After this PR:
```julia
julia> machine(model, X, y)
┌ Warning: The number and/or types of data arguments do not match what the specified model
│ supports. Suppress this type check by specifying `scitype_check_level=0`.
│ 
│ Run `@doc MLJBase.ProbabilisticStack` to learn more about your model's requirements.
│ 
│ Commonly, but non exclusively, supervised models are constructed using the syntax
│ `machine(model, X, y)` or `machine(model, X, y, w)` while most other models are
│ constructed with `machine(model, X)`.  Here `X` are features, `y` a target, and `w`
│ sample or class weights.
│ 
│ In general, data in `machine(model, data...)` is expected to satisfy
│ 
│     scitype(data) <: MLJ.fit_data_scitype(model)
│ 
│ In the present case:
│ 
│ scitype(data) = …
```

Improve warning of machine constructor

---

test/composition/models/methods.jl

This is necessary to get tests passing on Julia nightly.

Test suite: modify some uses of `deepcopy`

---

src/machines.jl
test/machines.jl

Without this PR `feature_importances(mach)` won't work properly unless `reports_feature_importances(mach.model)=false`. Includes new test. 
cc @OkonSamuel

Fix a bug with `feature_importances(::Machine)`

---

src/hyperparam/one_dimensional_range_methods.jl
src/measures/finite.jl
src/resampling.jl

Unbound type parameters often cause performance issues and run time dispatch.
Issue found using https://github.com/JuliaLang/julia/pull/46608

remove unbound type parameters

---

src/composition/models/stacking.jl
test/composition/learning_networks/machines.jl
test/composition/models/stacking.jl

Currently `Stack` is implemented as a `Composite` model, an abstract type to be deprecated in favour of `NetworkComposite` added by #841.
This is mildly breaking, as indicated in #852.

Re-implement `Stack` as a `NetworkComposite` model

---

Project.toml
src/composition/models/deprecated_from_network.jl

Fix bug: `MLJBase.depwarn` should have been `Base.depwarn` in redefinition of deprecated `@from_network`. To address fail at https://github.com/OutlierDetectionJL/OutlierDetection.jl/pull/36

For a 0.21.2 release

---

src/measures/probabilistic.jl
src/measures/roc.jl
test/measures/probabilistic.jl

This PR fixes a bug in the existing auc computation. The existing implementation gave incorrect auc prediction compared to other packages (e.g sklearn) in the case where two or more samples in the prediction vector has the same `UnivariateFinite` distributions.
```julia
julia> y = categorical(["class_1","class_1","class_0","class_0","class_1","class_1","class_0"])
7-element CategoricalArrays.CategoricalArray{String,1,UInt32}:
"class_1"
"class_1"
"class_0"
"class_0"
"class_1"
"class_1"
"class_0"
julia> ŷ = UnivariateFinite(levels(y), [0.8,0.7,0.5,0.5,0.5,0.5,0.3], augment=true, pool=y)
7-element UnivariateFiniteVector{Multiclass{2}, String, UInt32, Float64}:
UnivariateFinite{Multiclass{2}}(class_0=>0.2, class_1=>0.8)
UnivariateFinite{Multiclass{2}}(class_0=>0.3, class_1=>0.7) …
```

fix bug in auc computation

---

.github/workflows/ci.yml
src/composition/models/stacking.jl
test/composition/models/stacking.jl

Closes #861
Adds a check on the base models in a `Stack` when `clean!` is called. As far as I can tell, I'm only ruling out models here that would lead to unexpected behaviour or confusing error messages.

Add check for base models in `Stack`

---

test/hyperparam/one_dimensional_range_methods.jl

After pushing a minor doc fix I noticed new hyperparameter `range` method test [failures in CI](https://github.com/JuliaAI/MLJBase.jl/actions/runs/4265391495/jobs/7424667486) over multiple Julia versions, clearly unrelated to the push. It's not clear to me what the origin of the new failure is. However, the test, which uses version-specific RNGs looks flawed to me and when I change to StableRNGs (this PR) the new tests pass. So I am not inclined to investigate any further.

Fix suspicious test that is failing on CI

---

src/resampling.jl

Closes #874.
```julia
custom_measure(x, y) = accuracy(x, y)
measures = [custom_measure, log_loss,  MulticlassPrecision()]
X, y = make_blobs()
y = coerce(y, OrderedFactor)
julia> evaluate(
ConstantClassifier(),
X,
y;
measures,
)
PerformanceEvaluation object with these fields:
measure, operation, measurement, per_fold,
per_observation, fitted_params_per_fold,
report_per_fold, train_test_rows
Extract:
┌──────────────────────────────────┬──────────────┬─────────────┬─────────┬──────────────────────────────────────────┐
│ measure                          │ operation    │ measurement │ 1.96*SE │ per_fold                                 │
├──────────────────────────────────┼──────────────┼─────────────┼─────────┼──────────────────────────────────────────┤
│ custom_measure                   │ …
```

Fix `evaluate` display incompatiblity with Term.jl

---

src/composition/models/stacking.jl
src/resampling.jl

This PR contains the changes related to functions that can be extended by any logger projects (in this case, mlflow). It contains:
- A `log_evaluation` function that receives a logger instance and a performance evaluation.  It can be extended by any project that logs to a platform.
- Adapting MLJBase functions that receive logger as argument.
This changes can be seen applied in [MLJFlow.jl](https://github.com/JuliaAI/MLJFlow.jl).
Useful links:
- alan-turing-institute/MLJ.jl#1029
- Old PR: #912

Preparing MLJBase to receive logger instances

---

src/composition/learning_networks/signatures.jl
src/operations.jl
test/composition/models/network_composite.jl

Patch to fix `StaticNetworkComposite` issue

---

src/composition/models/pipelines.jl
src/composition/models/transformed_target_model.jl
test/composition/models/pipelines.jl
test/composition/models/transformed_target_model.jl

Closes #856.
For release notes:
- (**breaking**) Disallow `target` keyword argument in `TransformedTargetModel(...)`. Use `transformer=...` instead`. (#856)

Remove `target` as alias for `transformer` in `TransformedTargetModel`

---

src/utilities.jl
test/composition/learning_networks/replace.jl
test/utilities.jl

This PR increases test coverage and unmasks a test that was previously orphaned

Improve test coverage

---

Project.toml
src/resampling.jl

- rescue orphaned docstring for evaluate!
- bump 1.0.1

Rescue the orphaned docstring for `evaluate` 

---

src/resampling.jl
test/resampling.jl

This PR fixes a problem when the model wrapped by a `Resampler` instance is mutated to one of different prediction type. I ran into this while working on https://github.com/JuliaAI/MLJTuning.jl/pull/201.
```julia
using MLJBase, MLJModels
KNNClassifier = @load KNNClassifier
knn = KNNClassifier()
cnst =DeterministicConstantClassifier()
X, y = make_blobs()
resampler = MLJBase.Resampler(model=knn, measure=accuracy, operation=nothing)
mach = machine(resampler, X, y) |> fit!
resampler.model = cnst
fit!(mach)
```

Fix Resampler update bug

---

src/hyperparam/one_dimensional_ranges.jl
test/hyperparam/one_dimensional_ranges.jl

This commit addresses issue #948 by updating the display of parameter ranges to include reduced significant digits.

Reduce sigdigits in parameter range display #948

---

Project.toml
src/composition/learning_networks/replace.jl
src/composition/models/network_composite.jl
src/machines.jl
test/machines.jl
test/resampling.jl

Fix problem with serialization of nested models when component model overload `save`/`restore`

---

Project.toml
src/composition/learning_networks/nodes.jl
src/sources.jl

The diagnostics currently fail in some cases because of access to non-existing fields of a `machine` when `machine` (attached to some `Node`) is actually `nothing`.

Fix some error message diagnostics

---

Project.toml
src/composition/models/pipelines.jl
src/composition/models/transformed_target_model.jl
src/machines.jl
test/_models/DecisionTree.jl
test/composition/models/network_composite.jl
test/composition/models/pipelines.jl
test/composition/models/transformed_target_model.jl

A model that supports features importances exposes these via the method `feature_importances`. However, these importances are hidden if the model is wrapped in `TransformedTargetModel` or is part of a pipeline. This PR implements `feature_importances` (and the trait `reports_feature_importances`) for these two wrappers by forwarding the atomic methods. 
For testing purposes, the test model `DecisionTreeClassifier` in /test/_models/DecisionTree.jl has been updated to support feature importances. 
@OkonSamuel

Allow `Pipeline` and `TransformedTargetModel` to support feature importances

---

Project.toml
src/composition/models/pipelines.jl

If a model does not support training losses then it must nevertheless return `nothing` (the fallback) but instead pipelines are throwing an error.

Fix problem with training losses for pipelines

---

Project.toml
src/composition/models/pipelines.jl

For a 1.2.1 release

---

src/data/data.jl

Add "julia> " to example REPL session to clearly indicate code. Also add semicolon to indicate that the output should not be considered.

Add prompt to docstring REPL example

---

test/hyperparam/one_dimensional_range_methods.jl

Resolves #971
I am perplexed about the sudden appearance of the fail in #971. It seems like an RNG issue, but we use StableRNGs in the  testing and the git blame shows no change to the relevant MLJBase code in > 4 years. Interestingly, #969, which has passed tests, now fails for me locally also. Tests are failing locally for me in Julia 1.6 and Julia 1.10.
The test currently failing relies completely on the stability of the RNG used. In this PR I replace the test with a more robust one, which still uses StableRNGs but only checks that the RNG-generated counts are within their expected 95% confidence intervals, instead of checking their precise values. This is a more correct test anyhow. 
I played around locally to ensure the tests only fails about 5% of the time, and then fixed the seed …

Make test of `iterator(...)` more robust

---

.github/workflows/ci.yml
Project.toml
src/MLJBase.jl
src/machines.jl
src/resampling.jl
test/machines.jl
test/resampling.jl

Partly addresses https://github.com/alan-turing-institute/MLJ.jl/issues/1105, and prepares for https://github.com/JuliaAI/MLJTuning.jl/pull/215.
~~This PR also drops the `per_fold` part of `PerformanceEvaluation` display. More often than not, the table does not fit with this in it. The display still includes the names of all accessible fields.~~ This PR also adjusts the display of `per_fold` information to mitigate issue with overly wide table.
Previously:
```julia
PerformanceEvaluation object with these fields:
model, measure, operation, measurement, per_fold,
per_observation, fitted_params_per_fold,
report_per_fold, train_test_rows, resampling, repeats
Extract:
┌─────────────┬──────────────┬─────────────┬─────────┬──────────────────────────────────────
│ measure     │ operation    │ …
```

Add `CompactPerformanceEvaluation` objects and the option in `evaluate!` to construct them

---

src/MLJBase.jl
src/resampling.jl
test/resampling.jl

Closes #967
To do post-PR:
- re-export `InSample` from MLJ? (tracked)

Add `InSample` resampling strategy

---

src/composition/learning_networks/nodes.jl
src/composition/learning_networks/signatures.jl
src/composition/models/stacking.jl
src/composition/models/transformed_target_model.jl
src/data/data.jl
src/data/datasets.jl
src/data/datasets_synthetic.jl
src/hyperparam/one_dimensional_range_methods.jl
src/machines.jl
src/resampling.jl
src/show.jl
src/sources.jl
src/utilities.jl

Fence/indent/dedent code samples in docstrings with proper language tags so that built-in julia help and Documenter.jl can pick them up.

Update docstring examples and code

---

src/MLJBase.jl
src/init.jl
src/machines.jl
src/resampling.jl
test/resampling.jl

A step towards resolution of #926; see also https://github.com/JuliaAI/MLJ.jl/issues/1124.
This PR:
- Adds a global constant, initialized in `__init__`, for a default logger, for use with MLJFlow, for example. 
- Adds a function `default_logger` for returning or resetting the default logger
- Changes the default value of the `logger` kwarg in `evaluate`, `evaluate!`, and `Resampler` from `nothing` to `default_logger()`.
- Implements `MLJBase.save(mach) = MLJBase.save(default_logger(), mach)` to save machines (as artifacts) at the default logger (assuming it supports this).
To do:

Add a default_logger

---

src/composition/learning_networks/nodes.jl
src/composition/learning_networks/signatures.jl
src/composition/models/pipelines.jl
src/data/data.jl
src/data/datasets.jl
src/data/datasets_synthetic.jl
src/hyperparam/one_dimensional_range_methods.jl
src/machines.jl
src/resampling.jl
src/show.jl
src/utilities.jl

Major changes:
- Use of ordered lists
- Addition of method headers
- More/fixed admonition blocks
- Fixed links
- Fixed fence code examples
For more details, please see the commit messages. Thank you!

Docstring patches

---

src/resampling.jl
test/resampling.jl

Currently a model in `evaluate`/`evaluate!` must subtype `Supervised` or `Annotator`. However, in the current implementation, all that's essential for the model is: 
- It implements a `predict` method
- It's `fit` method consumes a target `y` (which must be provided in the `evaluate` call, or `machine` constructor).
-  In the common case that `operation` is left unspecified, `MLJModelnterface.prediction_type` must be one of: `:deterministic`, `:probabilistic`, `:interval`. 
Subtypes of `Annotator` and `Supervised` (e.g,`Probabilistic`, `Deterministic`, `Interval`) have the obvious `prediction_type` fallbacks, but the fallback for `Unsupervised` models is `:unknown`. 
This PR:
- Removes the current model type restriction: Now any `<:Model` is now allowed.
- Adds the currently missing check …

Relax restrictions on model type in resampling (`evaluate!`)

---

.github/workflows/ci.yml
src/interface/data_utils.jl
test/interface/data_utils.jl
test/resampling.jl

This PR closes #991. It also fixes an unrelated test that seems to have been broken by recent Julia update. Something about the behaviour of `@doc`, it seems. 
@OkonSamuel Let me know if you had a better suggestion for this PR. Otherwise, please review.

Allow `selectcols` to have tuples as "indices" argument

---

Project.toml

New minor version tag needed because support for Julia version 1.6  is being dropped.

Bump 0.8.0

---

Project.toml
src/interface/data_utils.jl

https://github.com/JuliaAI/MLJBase.jl/pull/992 and thereby release 1.8.0 broke MLJBase:
```
ERROR: LoadError: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
You may need to write `f(x::Vararg{T})` rather than `f(x::Vararg{<:T})` or `f(x::Vararg{T}) where T` instead of `f(x::Vararg{T} where T)`.
Stacktrace:
[1] UnionAll(v::Any, t::Any)
@ Core ./boot.jl:299
[2] top-level scope
@ ~/.julia/packages/MLJBase/5aKTB/src/interface/data_utils.jl:133
[3] include(mod::Module, _path::String)
@ Base ./Base.jl:557
[4] include(x::String)
@ MLJBase ~/.julia/packages/MLJBase/5aKTB/src/MLJBase.jl:1
[5] top-level scope
@ ~/.julia/packages/MLJBase/5aKTB/src/MLJBase.jl:149
[6] include
@ ./Base.jl:557 [inlined]
[7] include_package_for_output(pkg::Base.PkgId, input::String, …
```

Fix deprecated `Vararg` expression

---

Project.toml
src/resampling.jl

For the release notes:
- Allow tuples, in addition to vectors, when specifying `resampling=...` in `evaluate/evaluate!`, and fix a mistake in the error message for invalid `resampling` values (#1010)

For a 1.9 release
